version: 1.0.0.{build}

clone_folder: c:\projects\myproject
  
before_build:
  - choco install mingw | Out-Null
  - ps: (cat .gitmodules) | %{$_ -replace "git@github.com:","https://github.com/"} | sc .gitmodules
  - ps: python .\fetchDependencies.p | Out-Null # do not proceed until completed 
  - mkdir bin
  - cd bin
  - cmake -G "MinGW Makefiles" .. 

build_script:
  - rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - cmake --build .

test_script:
  - cd c:\projects\myproject\bin
  - ctest
